# Merging

In [185]:
import pandas as pd

In [186]:
frame_1 = pd.DataFrame({'id' :['ball', 'pencil', 'pen', 'mug', 'astray'], 
                        'price': [12,11,44,21,23]})

In [187]:
frame_2 = pd.DataFrame({'id' :['ball', 'pencil', 'pen', 'mug', 'astray'], 
                        'color': ['white','red','red','black','blue']})

In [188]:
frame_1

       id  price
0    ball     12
1  pencil     11
2     pen     44
3     mug     21
4  astray     23

In [189]:
frame_2

       id  color
0    ball  white
1  pencil    red
2     pen    red
3     mug  black
4  astray   blue

In [190]:
pd.merge(frame_1,frame_2)

       id  price  color
0    ball     12  white
1  pencil     11    red
2     pen     44    red
3     mug     21  black
4  astray     23   blue

In [191]:
frame_3 = pd.DataFrame({'id' :['ball', 'pencil', 'pen', 'mug', 'astray'], 
                        'color': ['white','red','red','black','blue'],
                        'Brand' : ['OMG', 'ABC', 'ABC', 'POD', 'POD']})

In [192]:
pd.merge(frame_1, frame_3, on = 'id')

       id  price  color Brand
0    ball     12  white   OMG
1  pencil     11    red   ABC
2     pen     44    red   ABC
3     mug     21  black   POD
4  astray     23   blue   POD

In [193]:
pd.merge(frame_1, frame_3, on = "id", how='right')

       id  price  color Brand
0    ball     12  white   OMG
1  pencil     11    red   ABC
2     pen     44    red   ABC
3     mug     21  black   POD
4  astray     23   blue   POD

In [194]:
frame_4 = pd.DataFrame({'id' :['ball', 'pencil', 'pen', 'mug', 'astray'], 
                        'color': ['white','red','red','black','blue'],
                       'Brand' : ['OMG', 'POD', 'ABC', 'POD', 'ABC'],
                       'Sid' :['pencil', 'ball', 'pencil', 'pen','pen']})

In [195]:
pd.merge(frame_3, frame_4, on=['id', 'Brand'], how= 'outer')

       id color_x Brand color_y     Sid
0  astray     NaN   ABC    blue     pen
1  astray    blue   POD     NaN     NaN
2    ball   white   OMG   white  pencil
3     mug   black   POD   black     pen
4     pen     red   ABC     red  pencil
5  pencil     red   ABC     NaN     NaN
6  pencil     NaN   POD     red    ball

In [196]:
pd.merge(frame_3, frame_4, right_index= True, left_index=True)

     id_x color_x Brand_x    id_y color_y Brand_y     Sid
0    ball   white     OMG    ball   white     OMG  pencil
1  pencil     red     ABC  pencil     red     POD    ball
2     pen     red     ABC     pen     red     ABC  pencil
3     mug   black     POD     mug   black     POD     pen
4  astray    blue     POD  astray    blue     ABC     pen

In [197]:
frame_3.columns = ['id_2', 'color_2', 'Brand_2']

In [198]:
frame_4.join(frame_3)

       id  color Brand     Sid    id_2 color_2 Brand_2
0    ball  white   OMG  pencil    ball   white     OMG
1  pencil    red   POD    ball  pencil     red     ABC
2     pen    red   ABC  pencil     pen     red     ABC
3     mug  black   POD     pen     mug   black     POD
4  astray   blue   ABC     pen  astray    blue     POD

In [199]:
import json
import pandas as pd

In [200]:
df = pd.read_json(r"C:\Users\mk744\OneDrive - Poornima University\Desktop\response_2")

In [201]:
df

,@page,@numpages,@pagesize,@total,@start,@end,@uri,@firstpageuri,@previouspageuri,@nextpageuri,@lastpageuri,Actions
0,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15608.5845.152508', 'CampaignId': '156..."
1,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15586.5849.973054', 'CampaignId': '155..."
2,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15608.5852.367974', 'CampaignId': '156..."
3,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15586.5852.545775', 'CampaignId': '155..."
4,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '12282.5855.200384', 'CampaignId': '122..."
5,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15608.5857.372596', 'CampaignId': '156..."
6,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15608.5857.382671', 'CampaignId': '156..."
7,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15608.5857.420504', 'CampaignId': '156..."
8,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '12282.5858.1004297', 'CampaignId': '12..."
9,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '12282.5859.586146', 'CampaignId': '122..."
10,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '12282.5860.499035', 'CampaignId': '122..."
11,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '1733.5861.290975', 'CampaignId': '1733..."
12,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '12282.5863.526126', 'CampaignId': '122..."
13,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15608.5870.1069432', 'CampaignId': '15..."
14,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15608.5870.1295792', 'CampaignId': '15..."
15,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '19663.5871.988022', 'CampaignId': '196..."
16,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '19663.5875.161743', 'CampaignId': '196..."
17,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '19663.5878.731972', 'CampaignId': '196..."
18,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '9043.5880.175540', 'CampaignId': '9043..."
19,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '19663.5882.13215', 'CampaignId': '1966..."
20,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '12282.5883.243508', 'CampaignId': '122..."
21,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '19663.5885.1496226', 'CampaignId': '19..."
22,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '12282.5885.1510410', 'CampaignId': '12..."
23,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15586.5887.605527', 'CampaignId': '155..."
24,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15586.5889.923579', 'CampaignId': '155..."
25,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '18571.5889.1284183', 'CampaignId': '18..."
26,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '18571.5889.1285550', 'CampaignId': '18..."
27,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '18571.5889.1284497', 'CampaignId': '18..."
28,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '18571.5890.116941', 'CampaignId': '185..."
29,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '18571.5890.116969', 'CampaignId': '185..."
30,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15586.5894.611647', 'CampaignId': '155..."
31,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15586.5896.143176', 'CampaignId': '155..."
32,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '19663.5898.598328', 'CampaignId': '196..."
33,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '15586.5900.466349', 'CampaignId': '155..."
34,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '19663.5903.228902', 'CampaignId': '196..."
35,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '12282.5904.1653528', 'CampaignId': '12..."
36,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '9043.5909.1072551', 'CampaignId': '904..."
37,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '19663.5941.412343', 'CampaignId': '196..."
38,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '1733.5944.970057', 'CampaignId': '1733..."
39,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '12282.5957.127760', 'CampaignId': '122..."
40,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '19663.5959.147030', 'CampaignId': '196..."
41,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '19663.5963.179337', 'CampaignId': '196..."
42,1,1,2000,43,0,42,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...,"{'Id': '9634.5976.252090', 'CampaignId': '9634..."

In [202]:
df['Actions']

0     {'Id': '15608.5845.152508', 'CampaignId': '156...
1     {'Id': '15586.5849.973054', 'CampaignId': '155...
2     {'Id': '15608.5852.367974', 'CampaignId': '156...
3     {'Id': '15586.5852.545775', 'CampaignId': '155...
4     {'Id': '12282.5855.200384', 'CampaignId': '122...
5     {'Id': '15608.5857.372596', 'CampaignId': '156...
6     {'Id': '15608.5857.382671', 'CampaignId': '156...
7     {'Id': '15608.5857.420504', 'CampaignId': '156...
8     {'Id': '12282.5858.1004297', 'CampaignId': '12...
9     {'Id': '12282.5859.586146', 'CampaignId': '122...
10    {'Id': '12282.5860.499035', 'CampaignId': '122...
11    {'Id': '1733.5861.290975', 'CampaignId': '1733...
12    {'Id': '12282.5863.526126', 'CampaignId': '122...
13    {'Id': '15608.5870.1069432', 'CampaignId': '15...
14    {'Id': '15608.5870.1295792', 'CampaignId': '15...
15    {'Id': '19663.5871.988022', 'CampaignId': '196...
16    {'Id': '19663.5875.161743', 'CampaignId': '196...
17    {'Id': '19663.5878.731972', 'CampaignId': '196...
18    {'Id': '9043.5880.175540', 'CampaignId': '9043...
19    {'Id': '19663.5882.13215', 'CampaignId': '1966...
20    {'Id': '12282.5883.243508', 'CampaignId': '122...
21    {'Id': '19663.5885.1496226', 'CampaignId': '19...
22    {'Id': '12282.5885.1510410', 'CampaignId': '12...
23    {'Id': '15586.5887.605527', 'CampaignId': '155...
24    {'Id': '15586.5889.923579', 'CampaignId': '155...
25    {'Id': '18571.5889.1284183', 'CampaignId': '18...
26    {'Id': '18571.5889.1285550', 'CampaignId': '18...
27    {'Id': '18571.5889.1284497', 'CampaignId': '18...
28    {'Id': '18571.5890.116941', 'CampaignId': '185...
29    {'Id': '18571.5890.116969', 'CampaignId': '185...
30    {'Id': '15586.5894.611647', 'CampaignId': '155...
31    {'Id': '15586.5896.143176', 'CampaignId': '155...
32    {'Id': '19663.5898.598328', 'CampaignId': '196...
33    {'Id': '15586.5900.466349', 'CampaignId': '155...
34    {'Id': '19663.5903.228902', 'CampaignId': '196...
35    {'Id': '12282.5904.1653528', 'CampaignId': '12...
36    {'Id': '9043.5909.1072551', 'CampaignId': '904...
37    {'Id': '19663.5941.412343', 'CampaignId': '196...
38    {'Id': '1733.5944.970057', 'CampaignId': '1733...
39    {'Id': '12282.5957.127760', 'CampaignId': '122...
40    {'Id': '19663.5959.147030', 'CampaignId': '196...
41    {'Id': '19663.5963.179337', 'CampaignId': '196...
42    {'Id': '9634.5976.252090', 'CampaignId': '9634...
Name: Actions, dtype: object

In [203]:
df_1 = pd.DataFrame(df)

In [204]:
df_1 = pd.json_normalize(df['Actions'])

In [205]:
df_1.head()

,Id,CampaignId,CampaignName,ActionTrackerName,ActionTrackerId,EventCode,State,AdId,Payout,DeltaPayout,...,Oid,CustomerArea,CustomerCity,CustomerRegion,CustomerCountry,SubId1,SubId2,SubId3,SharedId,Uri
0,15608.5845.152508,15608,Airalo - The World's First eSIM Store,Sale,29336,,APPROVED,1268485,1.10,1.10,...,,N/A,Nova Iguaçu,Rio de Janeiro,BR,gmg,,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...
1,15586.5849.973054,15586,Wondershare Software,Online Sale,29280,,APPROVED,1266848,8.89,8.89,...,,N/A,Rio de Janeiro,Rio de Janeiro,BR,gmg,,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...
2,15608.5852.367974,15608,Airalo - The World's First eSIM Store,Sale,29336,,APPROVED,1268485,1.00,1.00,...,,N/A,Shrewsbury,Massachusetts,US,gmg,,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...
3,15586.5852.545775,15586,Wondershare Software,Online Sale,29280,,APPROVED,1266848,9.00,9.00,...,,N/A,Queens,New York,US,gmg,,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...
4,12282.5855.200384,12282,Hostinger,Online Sale,22574,,APPROVED,888231,27.55,27.55,...,,N/A,Feira de Santana,Bahia,BR,gmg,,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...

In [206]:
df_1.columns

Index(['Id', 'CampaignId', 'CampaignName', 'ActionTrackerName',
       'ActionTrackerId', 'EventCode', 'State', 'AdId', 'Payout',
       'DeltaPayout', 'IntendedPayout', 'Amount', 'DeltaAmount',
       'IntendedAmount', 'Currency', 'ReferringDate', 'EventDate',
       'CreationDate', 'LockingDate', 'ClearedDate', 'ReferringType',
       'ReferringDomain', 'PromoCode', 'Oid', 'CustomerArea', 'CustomerCity',
       'CustomerRegion', 'CustomerCountry', 'SubId1', 'SubId2', 'SubId3',
       'SharedId', 'Uri'],
      dtype='object')

In [207]:
df_1[['Payout','DeltaPayout', 'IntendedPayout', 'Amount', 'DeltaAmount',
       'IntendedAmount', 'Currency', 'ReferringDate', 'EventDate',
       'CreationDate', 'LockingDate', 'ClearedDate']]

,Payout,DeltaPayout,IntendedPayout,Amount,DeltaAmount,IntendedAmount,Currency,ReferringDate,EventDate,CreationDate,LockingDate,ClearedDate
0,1.10,1.10,1.10,11.00,11.00,11.00,USD,2024-01-02T18:36:44+05:30,2024-01-02T18:38:35+05:30,2024-01-02T18:46:14+05:30,2024-02-08T05:30:00+05:30,2024-02-28T05:51:11+05:30
1,8.89,8.89,8.89,29.64,29.64,29.64,USD,2024-01-07T04:46:22+05:30,2024-01-07T04:46:24+05:30,2024-01-07T04:54:26+05:30,2024-02-28T10:30:00+05:30,2024-03-26T09:50:39+05:30
2,1.00,1.00,1.00,10.00,10.00,10.00,USD,2024-01-09T22:56:10+05:30,2024-01-09T22:58:57+05:30,2024-01-09T23:07:16+05:30,2024-02-08T05:30:00+05:30,2024-02-28T05:51:11+05:30
3,9.00,9.00,9.00,29.99,29.99,29.99,USD,2024-01-10T00:40:30+05:30,2024-01-10T00:41:11+05:30,2024-01-10T00:50:40+05:30,2024-02-28T10:30:00+05:30,2024-03-26T09:50:39+05:30
4,27.55,27.55,27.55,68.88,68.88,68.88,USD,2024-01-12T19:36:40+05:30,2024-01-12T19:37:04+05:30,2024-01-12T19:44:13+05:30,2024-03-16T02:30:00+05:30,2024-04-14T02:41:16+05:30
5,0.60,0.60,0.60,6.00,6.00,6.00,USD,2024-01-14T23:06:50+05:30,2024-01-14T23:07:45+05:30,2024-01-14T23:15:15+05:30,2024-02-08T05:30:00+05:30,2024-02-28T05:51:11+05:30
6,0.60,0.60,0.60,6.00,6.00,6.00,USD,2024-01-14T23:13:49+05:30,2024-01-14T23:18:25+05:30,2024-01-14T23:26:14+05:30,2024-02-08T05:30:00+05:30,2024-02-28T05:51:11+05:30
7,0.45,0.45,0.45,4.50,4.50,4.50,USD,2024-01-14T23:57:43+05:30,2024-01-14T23:58:28+05:30,2024-01-15T00:07:18+05:30,2024-02-08T05:30:00+05:30,2024-02-28T05:51:11+05:30
8,15.72,15.72,15.72,39.30,39.30,39.30,USD,2024-01-16T06:45:09+05:30,2024-01-16T06:46:15+05:30,2024-01-16T06:54:22+05:30,2024-03-16T02:30:00+05:30,2024-04-14T02:41:16+05:30
9,15.97,15.97,15.97,39.94,39.94,39.94,USD,2024-01-17T00:46:25+05:30,2024-01-17T00:52:09+05:30,2024-01-17T01:01:33+05:30,2024-03-16T02:30:00+05:30,2024-04-14T02:41:16+05:30
10,17.53,17.53,17.53,43.82,43.82,43.82,USD,2024-01-18T01:11:25+05:30,2024-01-18T01:11:37+05:30,2024-01-18T01:20:44+05:30,2024-03-16T02:30:00+05:30,2024-04-14T02:41:16+05:30
11,3.06,3.06,3.06,30.55,30.55,30.55,USD,2024-01-16T21:20:15+05:30,2024-01-18T22:02:41+05:30,2024-01-18T22:11:17+05:30,2024-02-16T13:30:00+05:30,2024-02-16T14:07:09+05:30
12,161.47,161.47,161.47,403.66,403.66,403.66,USD,2024-01-20T23:33:21+05:30,2024-01-20T23:41:41+05:30,2024-01-20T23:50:19+05:30,2024-03-16T02:30:00+05:30,2024-04-14T02:41:16+05:30
13,0.45,0.45,0.45,4.50,4.50,4.50,USD,2024-01-28T09:58:29+05:30,2024-01-28T09:58:32+05:30,2024-01-28T10:08:12+05:30,2024-02-08T05:30:00+05:30,2024-02-28T05:51:11+05:30
14,0.85,0.85,0.85,8.50,8.50,8.50,USD,2024-01-28T12:58:54+05:30,2024-01-28T13:04:19+05:30,2024-01-28T13:13:15+05:30,2024-02-08T05:30:00+05:30,2024-02-28T05:51:11+05:30
15,3.50,3.50,3.50,69.99,69.99,69.99,USD,2024-01-29T06:19:23+05:30,2024-01-29T06:20:31+05:30,2024-01-29T06:28:20+05:30,2024-02-27T21:30:00+05:30,2024-03-20T21:58:23+05:30
16,0.00,0.00,3.62,0.00,0.00,72.37,USD,2024-02-01T18:44:09+05:30,2024-02-01T18:44:13+05:30,2024-02-01T18:53:12+05:30,2024-03-20T21:30:00+05:30,2024-04-20T22:00:00+05:30
17,3.29,3.29,3.29,65.76,65.76,65.76,USD,2024-02-05T02:37:21+05:30,2024-02-05T02:37:24+05:30,2024-02-05T02:46:18+05:30,2024-03-20T21:30:00+05:30,2024-04-20T22:00:00+05:30
18,0.00,0.00,22.95,0.00,0.00,57.38,USD,2024-02-06T18:51:21+05:30,2024-02-06T18:53:00+05:30,2024-02-06T19:04:13+05:30,2024-04-16T02:30:00+05:30,
19,4.60,4.60,4.60,91.50,91.50,91.50,USD,2024-02-08T04:08:42+05:30,2024-02-08T13:59:35+05:30,2024-02-08T14:09:13+05:30,2024-03-20T21:30:00+05:30,2024-04-20T22:00:00+05:30
20,65.30,65.30,65.30,163.24,163.24,163.24,USD,2024-02-09T20:06:55+05:30,2024-02-09T20:08:47+05:30,2024-02-09T20:20:22+05:30,2024-04-16T02:30:00+05:30,2024-05-15T02:43:23+05:30
21,0.00,0.00,3.02,0.00,0.00,60.37,USD,2024-02-12T12:54:22+05:30,2024-02-12T12:55:55+05:30,2024-02-12T13:04:14+05:30,2024-03-20T21:30:00+05:30,2024-04-20T22:00:00+05:30
22,43.10,43.10,43.10,107.76,107.76,107.76,USD,2024-02-12T12:59:46+05:30,2024-02-12T13:24:45+05:30,2024-02-12T13:37:34+05:30,2024-04-16T02:30:00+05:30,2024-05-15T02:43:23+05:30
23,0.00,0.00,0.00,0.00,0.00,0.00,USD,2024-02-14T01:13:19+05:30,2024-02-14T01:14:25+05:30,2024-02-14T01:24:12+05:30,2024-03-28T09:30:00+05:30,2024-05-07T18:20:54+05:30
24,9.00,9.00,9.00,29.99,29.99,29.99,USD,2024-02-16T05:44:08+05:30,2024-02-16T05:44:44+05:30,2024-02-16T05:53:20+05:30,2024-03-28T09:30:00+05:30,2024-05-07T18:20:54+05:30
25,0.00,0.00,0.00,0.00,0.00,0.00,USD,2024-02-16T10:41:37+05:30,2024-02-16T10:42:16+05:30,2024-02-16T10:51:19+05:30,2024-03-14T12:30:00+05:30,
26,0.00,0.00,0.00,0.00,0.00,0.00,USD,2024-02-16T10:41:37+05:30,2024-02-16T10:43:51+05:30,2024-02-16T10:53:13+05:30,2024-03-14T12:30:00+05:30,
27,0.00,0.00,0.00,0.00,0.00,0.00,USD,2024-02-16T10:41:37+05:30,2024-02-16T10:44:05+05:30,2024-02-16T10:53:12+05:30,2024-03-14T12:30:00+05:30,
28,0.00,0.00,0.00,0.00,0.00,0.00,USD,2024-02-16T17:25:03+05:30,2024-02-16T17:26:26+05:30,2024-02-16T17:35:17+05:30,2024-03-15T12:30:00+05:30,
29,0.00,0.00,0.00,0.00,0.00,0.00,USD,2024-02-16T17:25:03+05:30,2024-02-16T17:26:42+05:30,2024-02-16T17:35:17+05:30,2024-03-15T12:30:00+05:30,
30,16.49,16.49,16.49,54.94,54.94,54.94,USD,2024-02-21T01:50:57+05:30,2024-02-21T01:51:06+05:30,2024-02-21T01:59:26+05:30,2024-03-28T09:30:00+05:30,2024-05-07T18:20:54+05:30
31,10.63,10.63,10.63,35.43,35.43,35.43,USD,2024-02-22T18:37:24+05:30,2024-02-22T18:37:26+05:30,2024-02-22T18:45:16+05:30,2024-03-28T09:30:00+05:30,2024-05-07T18:20:54+05:30
32,0.00,0.00,39.88,0.00,0.00,797.56,USD,2024-02-25T01:10:11+05:30,2024-02-25T01:10:14+05:30,2024-02-25T01:18:14+05:30,2024-03-20T21:30:00+05:30,2024-04-20T22:00:00+05:30
33,21.00,21.00,21.00,69.99,69.99,69.99,USD,2024-02-26T23:16:16+05:30,2024-02-26T23:17:11+05:30,2024-02-26T23:26:32+05:30,2024-03-28T09:30:00+05:30,2024-05-07T18:20:54+05:30
34,0.00,0.00,2.76,0.00,0.00,55.24,USD,2024-02-29T20:02:23+05:30,2024-02-29T20:03:06+05:30,2024-02-29T20:12:14+05:30,2024-03-20T21:30:00+05:30,2024-04-20T22:00:00+05:30
35,56.11,56.11,56.11,140.29,140.29,140.29,USD,2024-03-02T10:17:05+05:30,2024-03-02T10:45:36+05:30,2024-03-02T22:44:47+05:30,2024-05-16T02:30:00+05:30,
36,21.25,21.25,21.25,53.13,53.13,53.13,USD,2024-03-07T04:47:27+05:30,2024-03-07T04:49:00+05:30,2024-03-07T06:04:12+05:30,2024-05-16T02:30:00+05:30,
37,17.02,17.02,17.02,340.30,340.30,340.30,USD,2024-04-07T22:15:27+05:30,2024-04-07T22:15:30+05:30,2024-04-07T22:26:16+05:30,2024-05-20T21:30:00+05:30,
38,7.20,7.20,7.20,71.96,71.96,71.96,USD,2024-04-11T06:12:08+05:30,2024-04-11T06:15:28+05:30,2024-04-11T06:25:15+05:30,2024-05-16T12:30:00+05:30,2024-05-20T11:31:57+05:30
39,15.29,15.29,15.29,38.23,38.23,38.23,USD,2024-04-23T02:55:08+05:30,2024-04-23T17:44:02+05:30,2024-04-23T17:54:21+05:30,2024-06-16T02:30:00+05:30,
40,3.85,3.85,3.85,77.01,77.01,77.01,USD,2024-04-25T18:29:34+05:30,2024-04-25T18:30:38+05:30,2024-04-25T18:40:19+05:30,2024-05-20T21:30:00+05:30,
41,0.00,0.00,31.70,0.00,0.00,634.10,USD,2024-04-29T19:26:41+05:30,2024-04-29T19:27:20+05:30,2024-04-29T19:37:18+05:30,2024-05-20T21:30:00+05:30,
42,59.63,59.63,59.63,851.86,851.86,851.86,USD,2024-05-12T19:37:14+05:30,2024-05-12T19:52:28+05:30,2024-05-12T20:03:25+05:30,2024-07-16T00:00:00+05:30,

In [208]:
df_1.isnull().sum()

Id                   0
CampaignId           0
CampaignName         0
ActionTrackerName    0
ActionTrackerId      0
EventCode            0
State                0
AdId                 0
Payout               0
DeltaPayout          0
IntendedPayout       0
Amount               0
DeltaAmount          0
IntendedAmount       0
Currency             0
ReferringDate        0
EventDate            0
CreationDate         0
LockingDate          0
ClearedDate          0
ReferringType        0
ReferringDomain      0
PromoCode            1
Oid                  0
CustomerArea         0
CustomerCity         0
CustomerRegion       0
CustomerCountry      0
SubId1               0
SubId2               0
SubId3               0
SharedId             0
Uri                  0
dtype: int64

In [209]:
df_1.dtypes

Id                   object
CampaignId           object
CampaignName         object
ActionTrackerName    object
ActionTrackerId      object
EventCode            object
State                object
AdId                 object
Payout               object
DeltaPayout          object
IntendedPayout       object
Amount               object
DeltaAmount          object
IntendedAmount       object
Currency             object
ReferringDate        object
EventDate            object
CreationDate         object
LockingDate          object
ClearedDate          object
ReferringType        object
ReferringDomain      object
PromoCode            object
Oid                  object
CustomerArea         object
CustomerCity         object
CustomerRegion       object
CustomerCountry      object
SubId1               object
SubId2               object
SubId3               object
SharedId             object
Uri                  object
dtype: object

In [217]:
df_1.describe()

,Id,CampaignId,CampaignName,ActionTrackerName,ActionTrackerId,EventCode,State,AdId,Payout,DeltaPayout,...,Oid,CustomerArea,CustomerCity,CustomerRegion,CustomerCountry,SubId1,SubId2,SubId3,SharedId,Uri
count,43,43,43,43,43,43,43,43,43,43,...,43,43,43,43,43,43,43,43,43,43
unique,43,8,8,7,9,1,3,8,29,29,...,1,2,34,29,14,5,3,2,1,43
top,15608.5845.152508,19663,ELEGOO,Online Sale,22574,,APPROVED,1692726,0.00,0.00,...,,N/A,Jaipur,Rajasthan,IN,gmg,,,,/Mediapartners/IRXXsjceaKKb3321333MEX88pArHEUW...
freq,1,10,10,17,9,43,35,10,12,12,...,43,41,6,6,9,37,40,40,43,1

In [211]:
ans = df_1[['CampaignName', 'State','Payout','Amount','CustomerCity', 'CustomerRegion', 'CustomerCountry', 'CreationDate', 'Currency',
            'Id','SubId1']]

In [212]:
import warnings
warnings.filterwarnings('ignore')
ans['CreationDate'] = pd.to_datetime(ans['CreationDate'], utc=True)
ans['CreationDate'] = ans['CreationDate'].dt.date

In [213]:
ans['Payout'] = pd.to_numeric(ans['Payout'], errors='coerce')
ans['Payout_INR'] = 83.50 * ans['Payout']

In [214]:
ans.rename(columns={'State' : 'Status'}, inplace= True)

In [218]:
ans

,CampaignName,Status,Payout,Amount,CustomerCity,CustomerRegion,CustomerCountry,CreationDate,Currency,Id,SubId1,Payout_INR
0,Airalo - The World's First eSIM Store,APPROVED,1.10,11.00,Nova Iguaçu,Rio de Janeiro,BR,2024-01-02,USD,15608.5845.152508,gmg,91.850
1,Wondershare Software,APPROVED,8.89,29.64,Rio de Janeiro,Rio de Janeiro,BR,2024-01-06,USD,15586.5849.973054,gmg,742.315
2,Airalo - The World's First eSIM Store,APPROVED,1.00,10.00,Shrewsbury,Massachusetts,US,2024-01-09,USD,15608.5852.367974,gmg,83.500
3,Wondershare Software,APPROVED,9.00,29.99,Queens,New York,US,2024-01-09,USD,15586.5852.545775,gmg,751.500
4,Hostinger,APPROVED,27.55,68.88,Feira de Santana,Bahia,BR,2024-01-12,USD,12282.5855.200384,gmg,2300.425
5,Airalo - The World's First eSIM Store,APPROVED,0.60,6.00,Ronda,Andalusia,ES,2024-01-14,USD,15608.5857.372596,gmg,50.100
6,Airalo - The World's First eSIM Store,APPROVED,0.60,6.00,Ronda,Andalusia,ES,2024-01-14,USD,15608.5857.382671,gmg,50.100
7,Airalo - The World's First eSIM Store,APPROVED,0.45,4.50,Ronda,Andalusia,ES,2024-01-14,USD,15608.5857.420504,gmg,37.575
8,Hostinger,APPROVED,15.72,39.30,Totana,Murcia,ES,2024-01-16,USD,12282.5858.1004297,gmg,1312.620
9,Hostinger,APPROVED,15.97,39.94,Juiz de Fora,Minas Gerais,BR,2024-01-16,USD,12282.5859.586146,gmg,1333.495
10,Hostinger,APPROVED,17.53,43.82,Guarulhos,Sao Paulo,BR,2024-01-17,USD,12282.5860.499035,gmg,1463.755
11,MacPaw,APPROVED,3.06,30.55,Guadalajara,Jalisco,MX,2024-01-18,USD,1733.5861.290975,fs,255.510
12,Hostinger,APPROVED,161.47,403.66,Gurugram,Haryana,IN,2024-01-20,USD,12282.5863.526126,5OeGY7jsA24KrYMsSrKb,13482.745
13,Airalo - The World's First eSIM Store,APPROVED,0.45,4.50,Palo Negro,Aragua,VE,2024-01-28,USD,15608.5870.1069432,gmg,37.575
14,Airalo - The World's First eSIM Store,APPROVED,0.85,8.50,Singapore,n/a,SG,2024-01-28,USD,15608.5870.1295792,gmg,70.975
15,ELEGOO,APPROVED,3.50,69.99,Sheffield,England,GB,2024-01-29,USD,19663.5871.988022,gmg,292.250
16,ELEGOO,REVERSED,0.00,0.00,Gelsenkirchen,North Rhine-Westphalia,DE,2024-02-01,USD,19663.5875.161743,gmg,0.000
17,ELEGOO,APPROVED,3.29,65.76,Gelsenkirchen,North Rhine-Westphalia,DE,2024-02-04,USD,19663.5878.731972,gmg,274.715
18,Surfshark,REVERSED,0.00,0.00,Baraki,Shizuoka,JP,2024-02-06,USD,9043.5880.175540,gmg,0.000
19,ELEGOO,APPROVED,4.60,91.50,Gelsenkirchen,North Rhine-Westphalia,DE,2024-02-08,USD,19663.5882.13215,gmg,384.100
20,Hostinger,APPROVED,65.30,163.24,Palhoca,Santa Catarina,BR,2024-02-09,USD,12282.5883.243508,gmg,5452.550
21,ELEGOO,REVERSED,0.00,0.00,Bigues i Riells,Catalonia,ES,2024-02-12,USD,19663.5885.1496226,gmg,0.000
22,Hostinger,APPROVED,43.10,107.76,Winfield,West Virginia,US,2024-02-12,USD,12282.5885.1510410,gmg,3598.850
23,Wondershare Software,APPROVED,0.00,0.00,Odivelas,Lisbon,PT,2024-02-13,USD,15586.5887.605527,gmg,0.000
24,Wondershare Software,APPROVED,9.00,29.99,Afton,Virginia,US,2024-02-16,USD,15586.5889.923579,gmg,751.500
25,Spocket,APPROVED,0.00,0.00,Jaipur,Rajasthan,IN,2024-02-16,USD,18571.5889.1284183,gmg,0.000
26,Spocket,APPROVED,0.00,0.00,Jaipur,Rajasthan,IN,2024-02-16,USD,18571.5889.1285550,gmg,0.000
27,Spocket,APPROVED,0.00,0.00,Jaipur,Rajasthan,IN,2024-02-16,USD,18571.5889.1284497,gmg,0.000
28,Spocket,APPROVED,0.00,0.00,Jaipur,Rajasthan,IN,2024-02-16,USD,18571.5890.116941,gmg,0.000
29,Spocket,APPROVED,0.00,0.00,Jaipur,Rajasthan,IN,2024-02-16,USD,18571.5890.116969,gmg,0.000
30,Wondershare Software,APPROVED,16.49,54.94,Parkville,Maryland,US,2024-02-20,USD,15586.5894.611647,gmg,1376.915
31,Wondershare Software,APPROVED,10.63,35.43,Delhi,National Capital Territory of Delhi,IN,2024-02-22,USD,15586.5896.143176,fs,887.605
32,ELEGOO,REVERSED,0.00,0.00,Murcia,Murcia,ES,2024-02-24,USD,19663.5898.598328,gmg,0.000
33,Wondershare Software,APPROVED,21.00,69.99,Oklahoma City,Oklahoma,US,2024-02-26,USD,15586.5900.466349,gmg,1753.500
34,ELEGOO,REVERSED,0.00,0.00,Lünen,North Rhine-Westphalia,DE,2024-02-29,USD,19663.5903.228902,gmg,0.000
35,Hostinger,APPROVED,56.11,140.29,Jaipur,Rajasthan,IN,2024-03-02,USD,12282.5904.1653528,dyeCTkQvA7q7cyzChIkp,4685.185
36,Surfshark,APPROVED,21.25,53.13,Créteil,Île-de-France,FR,2024-03-07,USD,9043.5909.1072551,gmg,1774.375
37,ELEGOO,APPROVED,17.02,340.30,Lausanne,Vaud,CH,2024-04-07,USD,19663.5941.412343,gmg,1421.170
38,MacPaw,APPROVED,7.20,71.96,Buraidah,Al-Qassim Region,SA,2024-04-11,USD,1733.5944.970057,fs,601.200
39,Hostinger,PENDING,15.29,38.23,Barcelona,Catalonia,ES,2024-04-23,USD,12282.5957.127760,gmg,1276.715
40,ELEGOO,APPROVED,3.85,77.01,Granollers,Catalonia,ES,2024-04-25,USD,19663.5959.147030,gmg,321.475
41,ELEGOO,REVERSED,0.00,0.00,Mont-Saint-Martin,Grand Est,FR,2024-04-29,USD,19663.5963.179337,gmg,0.000
42,Lenovo India,PENDING,59.63,851.86,Dhanbad,Jharkhand,IN,2024-05-12,USD,9634.5976.252090,dykKX3Sm1GjFCXRSQxwh,4979.105

In [219]:
ans.describe()

           Payout    Payout_INR
count   43.000000     43.000000
mean    14.453488   1206.866279
std     28.305411   2363.501788
min      0.000000      0.000000
25%      0.000000      0.000000
50%      3.500000    292.250000
75%     16.230000   1355.205000
max    161.470000  13482.745000