In [1]:
val = 'a, b, guido'
val.split(',')

['a', ' b', ' guido']

In [2]:
pieces = [x.strip() for x in val.split(',')]

In [3]:
pieces

['a', 'b', 'guido']

In [4]:
'::'.join(pieces)

'a::b::guido'

In [5]:
import pandas as pd
Data = pd.read_csv(r"C:\Users\mk744\Downloads\Power BI project\Shoogloo XO CR Jan-24 to Apr-24.csv")

In [6]:
Data.head()

,conversion_id,click_id,campaign_id,campaign_name,conversion_method,country,city,isp,goal_id,goal_name,...,payout_in_campaign_currency,payout_in_user_currency,sale_amount_in_campaign_currency,sale_amount_in_user_currency,campaign_currency,created_date,created_time,Inventory,Partner,Email_id
0,65920089020cfa0516b79494,6591b701c93ae10341d0f461,4,Flipkart,acquisition,IN,Bantumilli,Airtel,NaN,Default,...,19.8,19.8,440.0,440.0,INR,1/1/2024,0:00:00,XO,Shoogloo,agoyal@flipshope.com
1,65920ebd00aa5d04e559bd70,65920579a32e370349dfb922,4,Flipkart,acquisition,IN,Gachibowli,Airtel Broadband,NaN,Default,...,12.6,12.6,274.0,274.0,INR,1/1/2024,0:00:00,XO,Shoogloo,agoyal@flipshope.com
2,659271fc971dbd04a5f3d618,659264cc67f02b03465efe14,4,Flipkart,acquisition,IN,Khurda,Jio,NaN,Default,...,13.5,13.5,379.0,379.0,INR,1/1/2024,0:00:00,XO,Shoogloo,agoyal@flipshope.com
3,6592720d5d41f8052403061d,659269027bd03f0345903b6d,4,Flipkart,acquisition,IN,Ahmedabad,Jio,NaN,Default,...,3.6,3.6,120.0,120.0,INR,1/1/2024,0:00:00,XO,Shoogloo,agoyal@flipshope.com
4,6592720d5d41f80524030639,65926924457fed033e5ca8bf,4,Flipkart,acquisition,IN,Hyderabad,Airtel,NaN,Default,...,3.6,3.6,124.0,124.0,INR,1/1/2024,0:00:00,XO,Shoogloo,agoyal@flipshope.com

In [7]:
Data['Email_id']

0       agoyal@flipshope.com
1       agoyal@flipshope.com
2       agoyal@flipshope.com
3       agoyal@flipshope.com
4       agoyal@flipshope.com
                ...
2944    agoyal@flipshope.com
2945    agoyal@flipshope.com
2946    agoyal@flipshope.com
2947    agoyal@flipshope.com
2948    agoyal@flipshope.com
Name: Email_id, Length: 2949, dtype: object

In [8]:
Data['Email_id'].value_counts()

Email_id
agoyal@flipshope.com    2949
Name: count, dtype: int64

In [9]:
# it find the length of agoyal@flipshope.com
Data['Email_id'].str.len().head()

0    20
1    20
2    20
3    20
4    20
Name: Email_id, dtype: int64

In [10]:
import pandas as pd

In [11]:
df=pd.read_json(r'C:\Users\mk744\OneDrive - Poornima University\Desktop\response.json')

In [12]:
df

,@page,@numpages,@pagesize,@total,@start,@end,@uri,@firstpageuri,@previouspageuri,@nextpageuri,@lastpageuri,Actions
0,1,3,2000,4213,0,1999,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,"{'Id': '7452.5843.843594', 'CampaignId': '7452..."
1,1,3,2000,4213,0,1999,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,"{'Id': 'M.9383.5843.1455152', 'CampaignId': '9..."
2,1,3,2000,4213,0,1999,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,"{'Id': '9383.5843.1416509', 'CampaignId': '938..."
3,1,3,2000,4213,0,1999,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,"{'Id': '9383.5843.1405596', 'CampaignId': '938..."
4,1,3,2000,4213,0,1999,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,"{'Id': '9383.5843.1486715', 'CampaignId': '938..."
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1,3,2000,4213,0,1999,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,"{'Id': '9383.5902.1908907', 'CampaignId': '938..."
1996,1,3,2000,4213,0,1999,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,"{'Id': '9383.5902.1775008', 'CampaignId': '938..."
1997,1,3,2000,4213,0,1999,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,"{'Id': '15890.5902.2015177', 'CampaignId': '15..."
1998,1,3,2000,4213,0,1999,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,"{'Id': '12108.5902.2026217', 'CampaignId': '12..."
1999,1,3,2000,4213,0,1999,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...,"{'Id': '15890.5902.2108688', 'CampaignId': '15..."

In [13]:
df.columns

Index(['@page', '@numpages', '@pagesize', '@total', '@start', '@end', '@uri',
       '@firstpageuri', '@previouspageuri', '@nextpageuri', '@lastpageuri',
       'Actions'],
      dtype='object')

In [14]:
df=df[[
       'Actions']]

In [15]:
df

                                                Actions
0     {'Id': '7452.5843.843594', 'CampaignId': '7452...
1     {'Id': 'M.9383.5843.1455152', 'CampaignId': '9...
2     {'Id': '9383.5843.1416509', 'CampaignId': '938...
3     {'Id': '9383.5843.1405596', 'CampaignId': '938...
4     {'Id': '9383.5843.1486715', 'CampaignId': '938...
...                                                 ...
1995  {'Id': '9383.5902.1908907', 'CampaignId': '938...
1996  {'Id': '9383.5902.1775008', 'CampaignId': '938...
1997  {'Id': '15890.5902.2015177', 'CampaignId': '15...
1998  {'Id': '12108.5902.2026217', 'CampaignId': '12...
1999  {'Id': '15890.5902.2108688', 'CampaignId': '15...

[2000 rows x 1 columns]

In [16]:
df1=pd.DataFrame(df)

In [17]:
df1=pd.json_normalize(df['Actions'])

In [18]:
df1

,Id,CampaignId,CampaignName,ActionTrackerName,ActionTrackerId,EventCode,State,AdId,Payout,DeltaPayout,...,Oid,CustomerArea,CustomerCity,CustomerRegion,CustomerCountry,SubId1,SubId2,SubId3,SharedId,Uri
0,7452.5843.843594,7452,NordVPN,New Customer Online Sale,13332,,REVERSED,417838,0.00,0.00,...,,N/A,Woodstock,Georgia,US,gmg,,,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...
1,M.9383.5843.1455152,9383,Walmart Affiliate Program,Online Sale,16681,,APPROVED,565706,0.11,0.11,...,,N/A,Webster,Texas,US,gmg,,,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...
2,9383.5843.1416509,9383,Walmart Affiliate Program,Online Sale,16681,,APPROVED,565706,0.00,0.00,...,,N/A,Kalamazoo,Michigan,US,gmg,,,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...
3,9383.5843.1405596,9383,Walmart Affiliate Program,Online Sale,16681,,APPROVED,565706,3.00,3.00,...,,N/A,San Antonio,Texas,US,gmg,,,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...
4,9383.5843.1486715,9383,Walmart Affiliate Program,Online Sale,16681,,APPROVED,565706,0.00,0.00,...,,N/A,Arlington,Virginia,US,gmg,,,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,9383.5902.1908907,9383,Walmart Affiliate Program,Online Sale,16681,,APPROVED,565706,0.00,0.00,...,,N/A,Pompano Beach,Florida,US,gmg,,,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...
1996,9383.5902.1775008,9383,Walmart Affiliate Program,Online Sale,16681,,APPROVED,565706,0.66,0.66,...,,N/A,Wenonah,New Jersey,US,gmg,,,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...
1997,15890.5902.2015177,15890,DigitalOcean,Account Activated,31631,,APPROVED,1297709,0.00,0.00,...,,N/A,Ashburn,Virginia,US,,,,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...
1998,12108.5902.2026217,12108,DHgate,Purchase,22237,,APPROVED,868543,40.98,40.98,...,,n/a,n/a,Louisiana,US,gmg,,,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...
1999,15890.5902.2108688,15890,DigitalOcean,Product Purchase,30097,,APPROVED,1297709,2.11,2.11,...,,N/A,Ashburn,Virginia,US,,,,,/Mediapartners/IRp5Wb4UaRqE3086640PGuK4cgHAiQy...

In [19]:
df1.columns

Index(['Id', 'CampaignId', 'CampaignName', 'ActionTrackerName',
       'ActionTrackerId', 'EventCode', 'State', 'AdId', 'Payout',
       'DeltaPayout', 'IntendedPayout', 'Amount', 'DeltaAmount',
       'IntendedAmount', 'Currency', 'ReferringDate', 'EventDate',
       'CreationDate', 'LockingDate', 'ClearedDate', 'ReferringType',
       'ReferringDomain', 'PromoCode', 'Oid', 'CustomerArea', 'CustomerCity',
       'CustomerRegion', 'CustomerCountry', 'SubId1', 'SubId2', 'SubId3',
       'SharedId', 'Uri'],
      dtype='object')

In [20]:
df1.to_csv('ZONET.csv')

In [21]:
select_relevent_col = df1[['Id','CampaignId', 'CampaignName', 'ActionTrackerName',
       'ActionTrackerId', 'EventCode', 'State', 'AdId', 'Payout',
       'DeltaPayout', 'IntendedPayout', 'Amount', 'IntendedAmount', 'Currency', 'ReferringDate', 'EventDate',
       'CreationDate', 'LockingDate', 'ClearedDate','CustomerArea', 'CustomerCity',
       'CustomerRegion', 'CustomerCountry', 'SubId1']]

In [22]:
select_relevent_col.head()

,Id,CampaignId,CampaignName,ActionTrackerName,ActionTrackerId,EventCode,State,AdId,Payout,DeltaPayout,...,ReferringDate,EventDate,CreationDate,LockingDate,ClearedDate,CustomerArea,CustomerCity,CustomerRegion,CustomerCountry,SubId1
0,7452.5843.843594,7452,NordVPN,New Customer Online Sale,13332,,REVERSED,417838,0.00,0.00,...,2023-12-31T16:39:34-08:00,2023-12-31T16:39:45-08:00,2023-12-31T16:48:19-08:00,2024-03-10T15:00:00-07:00,2024-05-02T02:04:36-07:00,N/A,Woodstock,Georgia,US,gmg
1,M.9383.5843.1455152,9383,Walmart Affiliate Program,Online Sale,16681,,APPROVED,565706,0.11,0.11,...,2023-12-31T12:37:39-08:00,2023-12-31T16:56:54-08:00,2024-01-01T14:07:27-08:00,2024-03-01T00:00:00-08:00,2024-04-24T03:08:09-07:00,N/A,Webster,Texas,US,gmg
2,9383.5843.1416509,9383,Walmart Affiliate Program,Online Sale,16681,,APPROVED,565706,0.00,0.00,...,2023-12-31T18:49:27-08:00,2023-12-31T18:49:28-08:00,2024-01-01T13:26:44-08:00,2024-03-01T00:00:00-08:00,2024-04-24T03:08:09-07:00,N/A,Kalamazoo,Michigan,US,gmg
3,9383.5843.1405596,9383,Walmart Affiliate Program,Online Sale,16681,,APPROVED,565706,3.00,3.00,...,2023-12-31T19:47:53-08:00,2023-12-31T19:48:14-08:00,2024-01-01T13:19:37-08:00,2024-03-01T00:00:00-08:00,2024-04-24T03:08:09-07:00,N/A,San Antonio,Texas,US,gmg
4,9383.5843.1486715,9383,Walmart Affiliate Program,Online Sale,16681,,APPROVED,565706,0.00,0.00,...,2023-12-31T19:49:26-08:00,2023-12-31T19:49:36-08:00,2024-01-01T14:48:33-08:00,2024-03-01T00:00:00-08:00,2024-04-24T03:08:09-07:00,N/A,Arlington,Virginia,US,gmg

In [23]:
select_relevent_col_1 = df1[['Id','CampaignId', 'CampaignName', 
        'State',  'Payout',
       'DeltaPayout', 'IntendedPayout', 'Amount', 'IntendedAmount', 'Currency',
       'CreationDate', 'CustomerCity',
       'CustomerRegion', 'CustomerCountry', 'SubId1']]

In [24]:
select_relevent_col_1.head()

,Id,CampaignId,CampaignName,State,Payout,DeltaPayout,IntendedPayout,Amount,IntendedAmount,Currency,CreationDate,CustomerCity,CustomerRegion,CustomerCountry,SubId1
0,7452.5843.843594,7452,NordVPN,REVERSED,0.00,0.00,5.20,0.00,12.99,USD,2023-12-31T16:48:19-08:00,Woodstock,Georgia,US,gmg
1,M.9383.5843.1455152,9383,Walmart Affiliate Program,APPROVED,0.11,0.11,0.11,31.97,31.97,USD,2024-01-01T14:07:27-08:00,Webster,Texas,US,gmg
2,9383.5843.1416509,9383,Walmart Affiliate Program,APPROVED,0.00,0.00,0.00,13.00,13.00,USD,2024-01-01T13:26:44-08:00,Kalamazoo,Michigan,US,gmg
3,9383.5843.1405596,9383,Walmart Affiliate Program,APPROVED,3.00,3.00,3.00,99.99,99.99,USD,2024-01-01T13:19:37-08:00,San Antonio,Texas,US,gmg
4,9383.5843.1486715,9383,Walmart Affiliate Program,APPROVED,0.00,0.00,0.00,8.99,8.99,USD,2024-01-01T14:48:33-08:00,Arlington,Virginia,US,gmg

In [25]:
import warnings
warnings.filterwarnings('ignore')
select_relevent_col_1.rename(columns = {'CampaignName' : 'Campaign_Name', 'State' : 'Status', 'CreationDate':"Date",
                                 'CustomerCity':'Customer_city', 'CustomerRegion':'Customer_Region', 'CustomerCountry': 'Customer_Country',
                                 'SubId1':'Sub_Id'}, inplace = True)

In [26]:
select_relevent_col_1.head()

,Id,CampaignId,Campaign_Name,Status,Payout,DeltaPayout,IntendedPayout,Amount,IntendedAmount,Currency,Date,Customer_city,Customer_Region,Customer_Country,Sub_Id
0,7452.5843.843594,7452,NordVPN,REVERSED,0.00,0.00,5.20,0.00,12.99,USD,2023-12-31T16:48:19-08:00,Woodstock,Georgia,US,gmg
1,M.9383.5843.1455152,9383,Walmart Affiliate Program,APPROVED,0.11,0.11,0.11,31.97,31.97,USD,2024-01-01T14:07:27-08:00,Webster,Texas,US,gmg
2,9383.5843.1416509,9383,Walmart Affiliate Program,APPROVED,0.00,0.00,0.00,13.00,13.00,USD,2024-01-01T13:26:44-08:00,Kalamazoo,Michigan,US,gmg
3,9383.5843.1405596,9383,Walmart Affiliate Program,APPROVED,3.00,3.00,3.00,99.99,99.99,USD,2024-01-01T13:19:37-08:00,San Antonio,Texas,US,gmg
4,9383.5843.1486715,9383,Walmart Affiliate Program,APPROVED,0.00,0.00,0.00,8.99,8.99,USD,2024-01-01T14:48:33-08:00,Arlington,Virginia,US,gmg

In [27]:
Data = select_relevent_col_1[['Campaign_Name', 'Status', 'Payout',
                              'Currency', 'Date', 'Customer_city',
                              'Customer_Region', 'Customer_Country',
                              'Sub_Id']]

In [28]:
Data.head()

,Campaign_Name,Status,Payout,Currency,Date,Customer_city,Customer_Region,Customer_Country,Sub_Id
0,NordVPN,REVERSED,0.00,USD,2023-12-31T16:48:19-08:00,Woodstock,Georgia,US,gmg
1,Walmart Affiliate Program,APPROVED,0.11,USD,2024-01-01T14:07:27-08:00,Webster,Texas,US,gmg
2,Walmart Affiliate Program,APPROVED,0.00,USD,2024-01-01T13:26:44-08:00,Kalamazoo,Michigan,US,gmg
3,Walmart Affiliate Program,APPROVED,3.00,USD,2024-01-01T13:19:37-08:00,San Antonio,Texas,US,gmg
4,Walmart Affiliate Program,APPROVED,0.00,USD,2024-01-01T14:48:33-08:00,Arlington,Virginia,US,gmg

In [29]:
from skimpy import skim
skim(Data)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 2000   │ │ string      │ 9     │                                                          │
│ │ Number of columns │ 9      │ └─────────────┴───────┘                                                          │
│ └───────────────────┴────────┘                                                                                  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column_name                      ┃ NA     ┃ NA %      ┃ words per row              ┃ total words           ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ Campaign_Name                    │      0 │         0 │                        2.7 │                  5451 │  │
│ │ Status                           │      0 │         0 │                          1 │                  2000 │  │
│ │ Payout                           │      0 │         0 │                          1 │                  2000 │  │
│ │ Currency                         │      0 │         0 │                          1 │                  2000 │  │
│ │ Date                             │      0 │         0 │                          1 │                  2000 │  │
│ │ Customer_city                    │      0 │         0 │                        1.3 │                  2506 │  │
│ │ Customer_Region                  │      0 │         0 │                        1.2 │                  2380 │  │
│ │ Customer_Country                 │      0 │         0 │                          1 │                  2000 │  │
│ │ Sub_Id                           │      0 │         0 │                          1 │                  2000 │  │
│ └──────────────────────────────────┴────────┴───────────┴────────────────────────────┴───────────────────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [30]:
import polars as pl

import pandas as pd
import seaborn as sns

from summarytools import dfSummary
from skimpy import skim
df_pl = pl.from_pandas(Data)
print(df_pl)

shape: (2_000, 9)
┌─────────────┬──────────┬────────┬──────────┬───┬─────────────┬─────────────┬────────────┬────────┐
│ Campaign_Na ┆ Status   ┆ Payout ┆ Currency ┆ … ┆ Customer_ci ┆ Customer_Re ┆ Customer_C ┆ Sub_Id │
│ me          ┆ ---      ┆ ---    ┆ ---      ┆   ┆ ty          ┆ gion        ┆ ountry     ┆ ---    │
│ ---         ┆ str      ┆ str    ┆ str      ┆   ┆ ---         ┆ ---         ┆ ---        ┆ str    │
│ str         ┆          ┆        ┆          ┆   ┆ str         ┆ str         ┆ str        ┆        │
╞═════════════╪══════════╪════════╪══════════╪═══╪═════════════╪═════════════╪════════════╪════════╡
│ NordVPN     ┆ REVERSED ┆ 0.00   ┆ USD      ┆ … ┆ Woodstock   ┆ Georgia     ┆ US         ┆ gmg    │
│ Walmart     ┆ APPROVED ┆ 0.11   ┆ USD      ┆ … ┆ Webster     ┆ Texas       ┆ US         ┆ gmg    │
│ Affiliate   ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ Program     ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ Walmart     ┆ APPROVED ┆ 0.00   ┆ USD      ┆ … ┆ Kalamazoo   ┆ Michigan    ┆ US         ┆ gmg    │
│ Affiliate   ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ Program     ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ Walmart     ┆ APPROVED ┆ 3.00   ┆ USD      ┆ … ┆ San Antonio ┆ Texas       ┆ US         ┆ gmg    │
│ Affiliate   ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ Program     ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ Walmart     ┆ APPROVED ┆ 0.00   ┆ USD      ┆ … ┆ Arlington   ┆ Virginia    ┆ US         ┆ gmg    │
│ Affiliate   ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ Program     ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ …           ┆ …        ┆ …      ┆ …        ┆ … ┆ …           ┆ …           ┆ …          ┆ …      │
│ Walmart     ┆ APPROVED ┆ 0.00   ┆ USD      ┆ … ┆ Pompano     ┆ Florida     ┆ US         ┆ gmg    │
│ Affiliate   ┆          ┆        ┆          ┆   ┆ Beach       ┆             ┆            ┆        │
│ Program     ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ Walmart     ┆ APPROVED ┆ 0.66   ┆ USD      ┆ … ┆ Wenonah     ┆ New Jersey  ┆ US         ┆ gmg    │
│ Affiliate   ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ Program     ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ DigitalOcea ┆ APPROVED ┆ 0.00   ┆ USD      ┆ … ┆ Ashburn     ┆ Virginia    ┆ US         ┆        │
│ n           ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
│ DHgate      ┆ APPROVED ┆ 40.98  ┆ USD      ┆ … ┆ n/a         ┆ Louisiana   ┆ US         ┆ gmg    │
│ DigitalOcea ┆ APPROVED ┆ 2.11   ┆ USD      ┆ … ┆ Ashburn     ┆ Virginia    ┆ US         ┆        │
│ n           ┆          ┆        ┆          ┆   ┆             ┆             ┆            ┆        │
└─────────────┴──────────┴────────┴──────────┴───┴─────────────┴─────────────┴────────────┴────────┘

In [31]:
dfSummary(Data)

In [32]:
Data['Date'] = pd.to_datetime(Data['Date'], errors='coerce')

In [33]:
Data.head()

,Campaign_Name,Status,Payout,Currency,Date,Customer_city,Customer_Region,Customer_Country,Sub_Id
0,NordVPN,REVERSED,0.00,USD,2023-12-31 16:48:19-08:00,Woodstock,Georgia,US,gmg
1,Walmart Affiliate Program,APPROVED,0.11,USD,2024-01-01 14:07:27-08:00,Webster,Texas,US,gmg
2,Walmart Affiliate Program,APPROVED,0.00,USD,2024-01-01 13:26:44-08:00,Kalamazoo,Michigan,US,gmg
3,Walmart Affiliate Program,APPROVED,3.00,USD,2024-01-01 13:19:37-08:00,San Antonio,Texas,US,gmg
4,Walmart Affiliate Program,APPROVED,0.00,USD,2024-01-01 14:48:33-08:00,Arlington,Virginia,US,gmg

In [34]:
# How to seperate Date from time
Data['Date'] = pd.to_datetime(Data['Date'], utc=True)
Data['Date'] = Data['Date'].dt.date
Data.head()

,Campaign_Name,Status,Payout,Currency,Date,Customer_city,Customer_Region,Customer_Country,Sub_Id
0,NordVPN,REVERSED,0.00,USD,2024-01-01,Woodstock,Georgia,US,gmg
1,Walmart Affiliate Program,APPROVED,0.11,USD,2024-01-01,Webster,Texas,US,gmg
2,Walmart Affiliate Program,APPROVED,0.00,USD,2024-01-01,Kalamazoo,Michigan,US,gmg
3,Walmart Affiliate Program,APPROVED,3.00,USD,2024-01-01,San Antonio,Texas,US,gmg
4,Walmart Affiliate Program,APPROVED,0.00,USD,2024-01-01,Arlington,Virginia,US,gmg

In [35]:
Data.to_csv('Cleaned_Data.csv')

In [40]:
select_relevent_col_1.head()

,Id,CampaignId,Campaign_Name,Status,Payout,DeltaPayout,IntendedPayout,Amount,IntendedAmount,Currency,Date,Customer_city,Customer_Region,Customer_Country,Sub_Id
0,7452.5843.843594,7452,NordVPN,REVERSED,0.00,0.00,5.20,0.00,12.99,USD,2023-12-31T16:48:19-08:00,Woodstock,Georgia,US,gmg
1,M.9383.5843.1455152,9383,Walmart Affiliate Program,APPROVED,0.11,0.11,0.11,31.97,31.97,USD,2024-01-01T14:07:27-08:00,Webster,Texas,US,gmg
2,9383.5843.1416509,9383,Walmart Affiliate Program,APPROVED,0.00,0.00,0.00,13.00,13.00,USD,2024-01-01T13:26:44-08:00,Kalamazoo,Michigan,US,gmg
3,9383.5843.1405596,9383,Walmart Affiliate Program,APPROVED,3.00,3.00,3.00,99.99,99.99,USD,2024-01-01T13:19:37-08:00,San Antonio,Texas,US,gmg
4,9383.5843.1486715,9383,Walmart Affiliate Program,APPROVED,0.00,0.00,0.00,8.99,8.99,USD,2024-01-01T14:48:33-08:00,Arlington,Virginia,US,gmg

In [41]:
df_1 = select_relevent_col_1[['Id', 'CampaignId', 'Campaign_Name', 'Status']]
df_2 = select_relevent_col_1[['Id', 'Campaign_Name','Payout', 'Currency']]

In [42]:
pd.merge(df_1, df_2, on='Id', how= 'outer')

,Id,CampaignId,Campaign_Name_x,Status,Campaign_Name_y,Payout,Currency
0,10168.5848.600219,10168,Envato Placeit,APPROVED,Envato Placeit,0.00,USD
1,10168.5855.1232502,10168,Envato Placeit,APPROVED,Envato Placeit,0.00,USD
2,10168.5865.609186,10168,Envato Placeit,APPROVED,Envato Placeit,0.00,USD
3,10168.5875.521297,10168,Envato Placeit,APPROVED,Envato Placeit,0.00,USD
4,10168.5875.615457,10168,Envato Placeit,APPROVED,Envato Placeit,0.00,USD
...,...,...,...,...,...,...,...
1995,M.9383.5902.1804350,9383,Walmart Affiliate Program,APPROVED,Walmart Affiliate Program,0.00,USD
1996,M.9383.5902.1873758,9383,Walmart Affiliate Program,APPROVED,Walmart Affiliate Program,0.02,USD
1997,M.9383.5902.1875138,9383,Walmart Affiliate Program,REVERSED,Walmart Affiliate Program,0.00,USD
1998,M.9383.5902.1960502,9383,Walmart Affiliate Program,APPROVED,Walmart Affiliate Program,0.02,USD
1999,M.9383.5902.1993726,9383,Walmart Affiliate Program,APPROVED,Walmart Affiliate Program,0.17,USD

In [47]:
df_2.columns = ['Id_1', 'Campaign_Name_1', 'Payout_1', 'Currency_1']

In [48]:
df_1.join(df_2)

,Id,CampaignId,Campaign_Name,Status,Id_1,Campaign_Name_1,Payout_1,Currency_1
0,7452.5843.843594,7452,NordVPN,REVERSED,7452.5843.843594,NordVPN,0.00,USD
1,M.9383.5843.1455152,9383,Walmart Affiliate Program,APPROVED,M.9383.5843.1455152,Walmart Affiliate Program,0.11,USD
2,9383.5843.1416509,9383,Walmart Affiliate Program,APPROVED,9383.5843.1416509,Walmart Affiliate Program,0.00,USD
3,9383.5843.1405596,9383,Walmart Affiliate Program,APPROVED,9383.5843.1405596,Walmart Affiliate Program,3.00,USD
4,9383.5843.1486715,9383,Walmart Affiliate Program,APPROVED,9383.5843.1486715,Walmart Affiliate Program,0.00,USD
...,...,...,...,...,...,...,...,...
1995,9383.5902.1908907,9383,Walmart Affiliate Program,APPROVED,9383.5902.1908907,Walmart Affiliate Program,0.00,USD
1996,9383.5902.1775008,9383,Walmart Affiliate Program,APPROVED,9383.5902.1775008,Walmart Affiliate Program,0.66,USD
1997,15890.5902.2015177,15890,DigitalOcean,APPROVED,15890.5902.2015177,DigitalOcean,0.00,USD
1998,12108.5902.2026217,12108,DHgate,APPROVED,12108.5902.2026217,DHgate,40.98,USD
1999,15890.5902.2108688,15890,DigitalOcean,APPROVED,15890.5902.2108688,DigitalOcean,2.11,USD